sudo: false
notifications:
  email: false


addons:
  firefox: "latest"

language: node_js
node_js:
  "node"

cache:
  directories:
    - node_modules

install:
  npm install

script:
  xvfb-run karma start --single-run --browsers Firefox --reporters dots
